### ISSUE TITLE
另一个模块牺牲了com.github.sharebooks: BookShared

### ISSUE THREAD

**Issue by zhoujiealex** [Xposed-Modules-Repo/cn.xihan.qdds#5]
大佬保护好自己

突然发现 近期的一个新模块 很强大，但是用了没一个月，整个项目都没了。
不知道去哪了，是不是动了qd的利益，被搞了

**Comment by xihan123** [comment]
> 大佬保护好自己
> 
> 突然发现 近期的一个新模块 很强大，但是用了没一个月，整个项目都没了。 不知道去哪了，是不是动了qd的利益，被搞了

消息还未解禁，暂时不能说更多，解禁后可能会详细说明
